[features]
seeds = false
[programs.devnet]
solana = "DruNnFeqLPnjG7xUJJrSdBYKALUodpa7ry4UKAuModQg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/danik/.config/solana/id.json"

[scripts]
test = "node tests/solana.js"
